{{- range .Values.namespaces }}
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .name }}-limitrange
  namespace: {{ .name }}
spec:
  limits:
    - type: Container
      {{- if .limitRange.defaultRequest }}
      defaultRequest:
        cpu: {{ .limitRange.defaultRequest.cpu | default "100m" }}
        memory: {{ .limitRange.defaultRequest.memory | default "128Mi" }}
      {{- end }}
      default:
        cpu: {{ .limitRange.default.cpu | default "500m" }}
        memory: {{ .limitRange.default.memory | default "512Mi" }}
      max:
        cpu: {{ .limitRange.max.cpu | default "2" }}
        memory: {{ .limitRange.max.memory | default "3Gi" }}
---
{{- end }}

